# Generated by Django 3.2.14 on 2022-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-03-20'),
            preserve_default=False,
        ),
    ]
